name: pong
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  copy_with_extension: ^4.0.4
  equatable: ^2.0.5
  flutter_screenutil: ^5.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  copy_with_extension_gen: ^4.0.4

flutter:
  fonts:
    - family: Pixeled
      fonts:
        - asset: lib/assets/fonts/Pixeled.ttf
